### ISSUE TITLE
Environment Configuration not always read

### ISSUE THREAD

**Issue by schmengler** [magium/Magium#114]
In the `EnvironmentConfigurationReader`, you use `$_ENV` to read all environment variables. Unfortunately many default PHP configurations have the ini setting "variables_order" set to "GPCS" so that the environment variables are only in `$_SERVER`, not in `$_ENV` (see: http://stackoverflow.com/questions/3780866/why-is-my-env-empty)

Changing the PHP configuration or running `php -dvariables_order=EGPCS vendor/bin/phpunit` solves the issue but I'd suggest to at least emit a warning if `$_ENV` is empty. Alternatively fall back to `$_SERVER` in this case.

**Comment by kschroeder** [comment]
Thanks for catching that.  I didn't have any unique settings in my original CI environment so I'm not quite sure why that was working.  Perhaps an old setting or something.  Now it does an array_merge on $_SERVER and $_ENV.
