### ISSUE TITLE
Dependecy on RandomLib

### ISSUE THREAD

**Issue by wasmitnetzen** [magium/Magium#198]
In [Util/Api/Clairvoyant/Clairvoyant.php#L17](https://github.com/magium/Magium/blob/master/lib/Util/Api/Clairvoyant/Clairvoyant.php#L17), there is RandomLib\Factory used which is required in [Clairvoyant.php#L141](https://github.com/magium/Magium/blob/master/lib/Util/Api/Clairvoyant/Clairvoyant.php#L141). I didn't find this library in composer.json or in the subsequent requirements.

**Comment by kschroeder** [comment]
Well, that is weird.  I've been using it for a year without that being a problem.  It looks like jeremykendall/query-auth requires it.  I've explicitly required it now in composer.json and released a new version.  Try running composer again and see if it works.

**Comment by wasmitnetzen** [comment]
Yeah, true, I can see jeremykendall/query-auth requiring it too here. Maybe I broke something.

**Comment by kschroeder** [comment]
Perhaps :-)

is it working now?

**Comment by wasmitnetzen** [comment]
Removed my local addition of the library in composer.json and ran the installation again, and it works. Looks indeed good now.
